name: Next.js

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Prettier
        run: yarn prettier:ci

      - name: Run ESLint
        run: yarn lint

      - name: Run TypeScript
        run: yarn typescript:ci

      - name: Run unit tests in CI environment
        run: yarn test:ci

      - name: Build the application
        run: yarn build
