name: Next.js

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      
      - name: Run Biome
        run: yarn biome:lint:ci

      - name: Run TypeScript
        run: yarn typescript:ci

      - name: Run unit tests in CI environment
        run: yarn test:ci

      - name: Build the application
        run: yarn build
